config/routes.rb
Rails.application.routes.draw do

  #---------------------------------------------------------------------------------------
  # public routes

  scope module: :public do
    # home
    root to: 'homes#top'
    get 'about', to: 'homes#about', as: 'about'

    # item
    resources :items, only: [:index, :show]

    # customer
    get 'customers/my_page', to: 'customers#show', as: 'public_customer_show'
    get 'customers/information/edit', to: 'customers#edit', as: 'public_customer_edit'
    patch 'customers/information', to: 'customers#update', as: 'public_customer_update'
    get 'customers/confirm', to: 'customers#confirm', as: 'public_customer_confirm'
    patch 'customers/withdraw', to: 'customers#withdraw', as: 'public_customer_withdraw'

    # cart_item
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    # order
    post 'orders/confirm', to: 'orders#confirm', as: 'confirm_order'
    get 'orders/complete', to: 'orders#complete', as: 'complete_order'
    resources :orders, only: [:new, :create, :index, :show]

    # delivery_address
    resources :delivery_addresses, only: [:index, :create, :destroy, :edit, :update]

  end

  # URL：/customers/sign_in
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #---------------------------------------------------------------------------------------
  # admin routes

  # URL：/admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # home
    root to: 'homes#top'

    # item
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # customer
    resources :customers, only: [:index, :show, :edit, :update]

    # order
    resources :orders, only: [:show, :update]

    # order_item
    resources :order_items, only: [:update]

    # genre
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :delivery_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord

  belongs_to :customer

  def delivery_address_display
    '〒' + postal_code + ' ' + address + '　' + name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  def get_item_image(size)

    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize: size).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum product_status: { start_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    purchase_price * amount
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customer_list = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genre_list = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @customer_list = Customer.all

    if params[:customer_id]
      @customer = @customer_list.find(params[:customer_id])
      all_order = @customer.orders

    else
      all_order = Order.all

    end

    @order_list = all_order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @item_list = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genre_list = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre_list = Genre.all
    @genre = @item.genre.name
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :genre_id, :price, :is_sold)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_item_list = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    @order_item_list = @order.order_items
    @order.update(order_status: params[:order][:order_status])

    if params[:order][:order_status] == Order.order_statuses.key(1)

      @order_item_list.each do |order_item|
        order_item.update(product_status: OrderItem.product_statuses.key(1))
      end

    end

    redirect_to admin_order_path(@order.id)

  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container ml-5">

  <div class = "h4 mt-4 ml-5 bg-light text-black text-center" style = "width:350px">
    &ensp;<%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集&ensp;
  </div>

  <div class = "mt-4 pl-5 mx-sm-0">

    <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>

      <div class = "d-flex align-items-center">
        <div style = "width: 200px">会員ID</div>
        <div style = "width: 260px">
           <%= @customer.id %>
        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-3 align-middle" style = "width: 200px">氏名</div>
        <div class = "mt-3" style = "width: 260px">
          <%= f.text_field :last_name, class: "form-control border-dark" %>
        </div>
        <div class = "mt-3" style = "width: 30px"></div>
        <div class = "mt-3" style = "width: 260px">
          <%= f.text_field :first_name, class: "form-control border-dark" %>
        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-3" style = "width: 200px">フリガナ</div>
        <div class = "mt-3" style = "width: 260px">
          <%= f.text_field :last_name_kana, class: "form-control border-dark" %>
        </div>
        <div class = "mt-3" style = "width: 30px"></div>
        <div class = "mt-3" style = "width: 260px">
            <%= f.text_field :first_name_kana, class: "form-control border-dark" %>
        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-3" style = "width: 200px">郵便番号</div>
        <div class = "mt-3" style = "width: 260px">
            <%= f.text_field :postal_code, class: "form-control border-dark" %>
        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-3" style = "width: 200px">住所</div>
        <div class = "mt-3" style = "width: 750px">
            <%= f.text_field :address, class: "form-control border-dark" %>
        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-3" style= "width: 200px">電話番号</div>
        <div class = "mt-3" style = "width: 260px">
            <%= f.text_field :telephone_number, class: "form-control border-dark" %>
        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-3" style = "width: 200px">メールアドレス</div>
        <div class = "mt-3" style = "width: 260px">
            <%= f.text_field :email, class: "form-control border-dark" %>
        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-3" style = "width: 200px">会員ステータス</div>
        <div class = "mt-4" style = "width: 260px">

          <!-- 有効時 -->
          <% if @customer.is_deleted == true %>
            <%= f.radio_button :is_deleted, :false%>
            <%= f.label :is_deleted, "有効" %>
            <%= f.radio_button :is_deleted, :true, class: "ml-4", checked: "checked" %>
            <%= f.label :is_deleted, "退会" %>

          <!-- 退会時 -->
          <% else %>
            <%= f.radio_button :is_deleted, :false, checked: "checked" %>
            <%= f.label :is_deleted, "有効" %>
            <%= f.radio_button :is_deleted, :true, class: "ml-4" %>
            <%= f.label :is_deleted, "退会" %>

          <% end %>

        </div>
      </div>

      <div class = "d-flex align-items-center">
        <div class = "mt-5" style = "width: 200px"></div>
        <div class = "mt-4" style = "width: 260px">
          <%= f.submit "変更を保存", class: "btn btn-success form-control  font-weight-bold col-7", style: "height: 40px" %>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/admin/customers/index.html.erb
<div class = "container">

  <div class = "h4 mt-4 bg-light text-black text-center" style = "width:150px">
    &ensp;会員一覧&ensp;
  </div>

  <div class = "row justify-content-center mt-4" style = "font-size:0.9rem">
    <table class = "table" style = "width: 750px">

      <thead class =  "bg-light">
        <tr>
          <th class = "p-2" style = "width: 100px">会員ID</th>
          <th class = "p-2" style = "width: 200px">氏名</th>
          <th class = "p-2" style = "width: 250px">メールアドレス</th>
          <th class = "p-2" style = "width: 200px">ステータス</th>
        </tr>
      </thead>

       <tbody>
         <% @customer_list.each do |customer| %>

          <tr class = "border-bottom">
            <td class = "align-middle" style = "width: 100px">
              <%= customer.id %>
            </td>
            <td class = "align-middle" style = "width: 200px">
              <%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class: "text-dark" %>
            </td>
            <td class = "align-middle" style = "width: 250px">
              <%= customer.email %>
            </td>
            <td class = "align-middle" style = "width: 200px">

              <!-- 退会時の処理 -->
              <% if customer.is_deleted == true %>
                <p class = "font-weight-bold m-0" style = "color: #CCCCCC">退会</p>

              <!-- 退会していない時の処理 -->
              <% else %>
                <p class = "font-weight-bold text-success m-0">有効</p>

              <% end %>
            </td>
          </tr>

        <% end %>
      </tbody>

      <tfoot>
        <tr>
          <td class = "align-middle"  colspan = "4">
            <%= paginate @customer_list %>
          </td>
        </tr>
      </tfoot>

    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class = "container">

  <div class = "h4 mt-4 bg-light text-black text-center" style = "width:350px">
    &ensp;<%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細&ensp;
  </div>

  <div class = "row ml-0 mt-4" style = "font-size:0.9rem">

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style = "width: 200px">会員ID</div>
      <div class = "pl-2 py-2" style = "width: 500px">
        <%= @customer.id %>
      </div>
    </div>

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style = "width: 200px">氏名</div>
      <div class = "pl-2 py-2" style= "width: 500px">
        <%= @customer.last_name %>&ensp;<%= @customer.first_name %>
      </div>
    </div>

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style = "width: 200px">フリガナ</div>
      <div class = "pl-2 py-2" style = "width: 500px">
        <%= @customer.last_name_kana %>&ensp;<%= @customer.first_name_kana %>
      </div>
    </div>

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style = "width: 200px">郵便番号</div>
      <div class = "pl-2 py-2" style = "width: 500px">
        <%= @customer.postal_code %>
      </div>
    </div>

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style= "width: 200px">住所</div>
      <div class = "pl-2 py-2" style= "width: 500px">
        <%= @customer.address %>
      </div>
    </div>

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style= "width: 200px">電話番号</div>
      <div class = "pl-2 py-2" style= "width: 500px">
        <%= @customer.telephone_number %>
      </div>
    </div>

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style= "width: 200px">メールアドレス</div>
      <div class = "pl-2 py-2" style= "width: 500px">
        <%= @customer.email %>
      </div>
    </div>

    <div class = "d-flex align-items-center">
      <div class = "pl-2 py-2" style= "width: 200px">会員ステータス</div>
      <div class = "pl-2 py-2" style= "width: 500px">

        <!-- 退会時の処理 -->
        <% if @customer.is_deleted == true %>
          <p class = "font-weight-bold m-0" style = "color: #CCCCCC">退会</p>

        <!-- 退会していない時の処理 -->
        <% else %>
          <p class = "font-weight-bold text-success m-0">有効</p>

        <% end %>

      </div>
    </div>

    <div class = "d-flex align-items-center mt-4">
      <div style = "width: 200px"></div>
      <div style = "width: 160px">
        <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success form-control col-12" %>
      </div>
      <div style = "width: 90px"></div>
      <div style = "width: 220px">
        <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary form-control col-12" %>
      </div>
    </div>

  </div>
</div>