config/routes.rb
Rails.application.routes.draw do

  #---------------------------------------------------------------------------------------
  # public routes

  scope module: :public do
    # home
    root to: 'homes#top'
    get 'about', to: 'homes#about', as: 'about'

    # item
    resources :items, only: [:index, :show]

    # customer
    get 'customers/my_page', to: 'customers#show', as: 'public_customer_show'
    get 'customers/information/edit', to: 'customers#edit', as: 'public_customer_edit'
    patch 'customers/information', to: 'customers#update', as: 'public_customer_update'
    get 'customers/confirm', to: 'customers#confirm', as: 'public_customer_confirm'
    patch 'customers/withdraw', to: 'customers#withdraw', as: 'public_customer_withdraw'

    # cart_item
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    # order
    post 'orders/confirm', to: 'orders#confirm', as: 'confirm_order'
    get 'orders/complete', to: 'orders#complete', as: 'complete_order'
    resources :orders, only: [:new, :create, :index, :show]

    # delivery_address
    resources :delivery_addresses, only: [:index, :create, :destroy, :edit, :update]

  end

  # URL：/customers/sign_in
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #---------------------------------------------------------------------------------------
  # admin routes

  # URL：/admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # home
    root to: 'homes#top'

    # item
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # customer
    resources :customers, only: [:index, :show, :edit, :update]

    # order
    resources :orders, only: [:show, :update]

    # order_item
    resources :order_items, only: [:update]

    # genre
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_item_list = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    @order_item_list = @order.order_items
    @order.update(order_status: params[:order][:order_status])

    if params[:order][:order_status] == Order.order_statuses.key(1)

      @order_item_list.each do |order_item|
        order_item.update(product_status: OrderItem.product_statuses.key(1))
      end

    end

    redirect_to admin_order_path(@order.id)

  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class = "container">

  <div class = "h4 mt-4 bg-light text-black text-center" style = "width:260px">
    &ensp;注文履歴詳細&ensp;
  </div>

</div>

<div class = "container-xxl ml-5 pl-5", style = "width: 1300px">

  <div class = "row mt-4 ml-3 pl-5">
    <span class = "h5 font-weight-bold" style = "width: 200px">
      購入者
    </span>
    <span style = "width: 300px; font-size:1.2rem">
      <%= link_to @order.customer.last_name + @order.customer.first_name,admin_root_path(customer_id: @order.customer_id), class: "text-dark" %>
    </span>
  </div>

  <div class = "row mt-2 ml-3 pl-5">
    <span class = "h5 font-weight-bold" style = "width: 200px">
      注文日
    </span>
    <span style = "width: 300px; font-size:1.2rem">
      <%= @order.created_at.strftime("%Y/%-m/%-d") %>
    </span>
  </div>

  <div class = "row mt-2 ml-3 pl-5">
    <span class = "h5 font-weight-bold" style = "width: 200px">
      配送先
    </span>
    <span style = "width: 800px; font-size:1.2rem">
      <%= '〒' + @order.postal_code + '　' + @order.address %></br>
      <%= @order.name %>
    </span>
  </div>

  <div class = "row mt-2 ml-3 pl-5">
    <span class = "h5 font-weight-bold" style = "width: 200px">
      支払方法
    </span>
    <span style = "width: 800px; font-size:1.2rem">
      <%= @order.payment_method_i18n %>
    <span>
  </div>

  <div class = "row mt-3 ml-3 pl-5">
    <span class = "h5 font-weight-bold" style = "width: 200px">
      注文ステータス
    </span>
    <span class = "order-status-select-design" style = "width: 800px; font-size:1.2rem">
      <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
        <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]}, options = { include_blank: false } %>
        <%= f.submit "更新", class: "btn btn-success form-control font-weight-bold ml-4 p-0", style: "width: 60px; height: 36px" %>
      <% end %>
    <span>
  </div>
</div>

<div class = "container-xxl ml-5 mt-4" style = "width: 1320px">

  <div class = "row mt-4 ml-5 pl-5">
    <div class = "col-9">

      <table class = "table" style = "width: 880px; font-size:0.9rem">

        <thead class =  "bg-light">
          <tr>
            <th style = "width: 250px">商品名</th>
            <th class = "text-center" style = "width: 120px">単価(税込)</th>
            <th class = "text-center" style = "width: 120px">数量</th>
            <th class = "text-center" style = "width: 120px">小計</th>
            <th class = "text-center" style = "width: 270px">製作ステータス</th>
          </tr>
        </thead>

        <tbody class = "border-bottom">
          <% @order_item_list.each do |order_item| %>

            <tr class>
              <td class = "align-middle" style = "width: 250px">
                <%= order_item.item.name %>
              </td>
              <td class = "align-middle text-center" style = "width: 120px">
                <%= order_item.purchase_price.to_s(:delimited) %>
              </td>
              <td class = "align-middle text-center" style = "width: 120px">
                <%= order_item.amount %>
              </td>
              <td class = "align-middle text-center" style = "width: 120px">
                <%= order_item.subtotal.to_s(:delimited) %>
              </td>
              <td class = "align-middle text-center" style = "width:270px">
                <div class = "product-status-select-design">
                  <%= form_with model: order_item, url: admin_order_item_path(order_item.id) do |f| %>
                    <%= f.select :product_status, OrderItem.product_statuses.keys.map {|k| [I18n.t("enums.order_item.product_status.#{k}"), k]}, options = { include_blank: false } %>
                    <%= f.submit "更新", class: "btn btn-success form-control font-weight-bold ml-3 p-0", style: "width: 60px; height: 36px" %>
                  <% end %>
                </div>
              </td>
            </tr>

          <% end %>
        </tbody>

      </table>

    </div>

    <div class = "col-1"></div>

    <div class = "col-2 px-0 mt-auto">
      <table class = "table table-borderless mb-0" style = "width: 220px">

        <tr style = "height: 30px">
          <td class = "px-0 py-2 align-middle font-weight-bold" style = "width: 120px">商品合計</td>
          <td class = "px-0 py-2 align-middle" style = "width: 100px">
            <%= @order.total_price.to_s(:delimited) %>円
          </td>
        </tr>

        <tr style = "height: 30px">
          <td class = "px-0 py-2 align-middle font-weight-bold" style = "width: 120px">送料</td>
          <td class = "px-0 py-2 align-middle", style = "width: 100px">
            <%= @order.postage.to_s(:delimited) %>円
          </td>
        </tr>

        <tr style = "height: 30px">
          <td class = "px-0 py-2 align-middle font-weight-bold" style = "width: 120px">請求金額合計</td>
          <td class = "px-0 py-2 align-middle font-weight-bold" style = "width: 100px">
            <%= (@order.total_price + @order.postage).to_s(:delimited) %>円
          </td>
        </tr>

      </table>
    </div>

  </div>

</div>