config/routes.rb
Rails.application.routes.draw do

  #---------------------------------------------------------------------------------------
  # public routes

  scope module: :public do
    # home
    root to: 'homes#top'
    get 'about', to: 'homes#about', as: 'about'

    # item
    resources :items, only: [:index, :show]

    # customer
    get 'customers/my_page', to: 'customers#show', as: 'public_customer_show'
    get 'customers/information/edit', to: 'customers#edit', as: 'public_customer_edit'
    patch 'customers/information', to: 'customers#update', as: 'public_customer_update'
    get 'customers/confirm', to: 'customers#confirm', as: 'public_customer_confirm'
    patch 'customers/withdraw', to: 'customers#withdraw', as: 'public_customer_withdraw'

    # cart_item
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    # order
    post 'orders/confirm', to: 'orders#confirm', as: 'confirm_order'
    get 'orders/complete', to: 'orders#complete', as: 'complete_order'
    resources :orders, only: [:new, :create, :index, :show]

    # delivery_address
    resources :delivery_addresses, only: [:index, :create, :destroy, :edit, :update]

  end

  # URL：/customers/sign_in
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #---------------------------------------------------------------------------------------
  # admin routes

  # URL：/admin/sign_in
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # home
    root to: 'homes#top'

    # item
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # customer
    resources :customers, only: [:index, :show, :edit, :update]

    # order
    resources :orders, only: [:show, :update]

    # order_item
    resources :order_items, only: [:update]

    # genre
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :delivery_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord

  belongs_to :customer

  def delivery_address_display
    '〒' + postal_code + ' ' + address + '　' + name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  def get_item_image(size)

    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize: size).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum product_status: { start_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    purchase_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genre_list = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @customer_list = Customer.all

    if params[:customer_id]
      @customer = @customer_list.find(params[:customer_id])
      all_order = @customer.orders

    else
      all_order = Order.all

    end

    @order_list = all_order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @item_list = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genre_list = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre_list = Genre.all
    @genre = @item.genre.name
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :name, :introduction, :genre_id, :price, :is_sold)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "こちら", new_session_path(resource_name) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="min-width:1350px">

    <!-- header(動的) -->
    <header>
      <nav class = "navbar navbar-expand-lg navbar-light border-secondary border-bottom pb-3" style = "background-color: white">
        <%= link_to "ながのCAKE", root_path, class: "navbar-brand border border-dark px-5 py-1 ml-4" %>

        <div class = "ml-5 pl-5 mt-3">

          <% if customer_signed_in? %>
            ようこそ、<%= current_customer.last_name %>さん！
          <% end %>

        </div>

        <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" aria-expanded = "false" aria-label = "Toggle navigation">
          <span class = "navbar-toggler-icon"></span>
        </button>
        <div class = "collapse navbar-collapse" id = "navbarNavDropdown">
          <ul class = "navbar-nav ml-auto my-4">

            <% if admin_signed_in? %>

              <li class = "nav-item">
                <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

            <% elsif customer_signed_in? %>

              <li class = "nav-item">
                <%= link_to "マイページ", public_customer_show_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

            <% else %>

              <li class = "nav-item">
                <%= link_to "About", about_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

              <li class = "nav-item">
                <%= link_to "　ログイン　", new_customer_session_path, class: "btn btn-outline-secondary mx-3 px-1", style: "width: 110px" %>
              </li>

            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <%= yield %>

  </body>
</html>